# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup googletest
        run: git clone https://github.com/google/googletest.git tests/googletest
      - name: cmake googletest
        run: cmake tests/googletest
      - name: make googletest
        run: make -C tests/googletest

      - name: Run cmake
        run: cmake .

      - name: Run make
        run: make
        
      - name: Run googletest
        run: tests/buflog_unittest.out
        
